### ISSUE TITLE
Adding https to piwheels.hostedpi.com?

### ISSUE THREAD

**Issue by Faqa** [bennuttall/piwheels#10]
As the title says. Is there any way that would be possible, on your end? We'd like to be able to use that server as part of our build process (and in doing so, help this project troubleshoot packages that are not building), but not at the cost of having to pull from a non-https source.

**Comment by bennuttall** [comment]
Definitely - it's something I'll be doing very shortly. The production server is now at http://www.piwheels.hostedpi.com/ - so it'll mean adding SSL to that.

**Comment by mishas** [comment]
It might be obvious, but may I suggest using https://letsencrypt.org/, it's free TLS for the crowds.

I also see that you're using hstedpi.com, which seem to support letsencrypt via API (checked here: https://www.mythic-beasts.com/)

**Comment by bennuttall** [comment]
That's the plan! Thanks for the heads up though

**Comment by bennuttall** [comment]
Done! :lock: https://www.piwheels.hostedpi.com/

:1st_place_medal:
