### ISSUE TITLE
Missing Package: cryptoauthlib

### ISSUE THREAD

**Issue by bryan-hunt** [bennuttall/piwheels#101]
Missing package
Package name: `cryptoauthlib`
Link to PyPI page: https://pypi.org/project/cryptoauthlib/
Link to piwheels page: https://www.piwheels.org/simple/cryptoauthlib
Version: `all`
More information:

I've tested the most recent release on a fresh Raspbian Stretch (2018-10-09) instance with the only change being installation of known requirements for this package (which are already listed in deploy_slave.sh) installing from pypi sources via pip and pip3.

**Comment by bennuttall** [comment]
Thanks for reporting. I've managed to get the latest version built for stretch, but failing to build for jessie (not sure why). I'll keep trying to figure it out and I'll try the older versions too. If you were after the latest version for Stretch / 3.5 then you should be ok.

**Comment by bennuttall** [comment]
It doesn't support Python 3.4, so the Jessie builds always fail. I don't know why the Stretch ones failed but I'll get it to retry them now.

**Comment by bennuttall** [comment]
Yeah it seems older versions don't build. This is the error from the previous version:

```
    File "/tmp/pip-wheel-v590i9lk/cryptoauthlib/setup.py", line 144, in build_extension
      stdin=devnull, stdout=devnull, stderr=devnull, shell=False)
    File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-wheel-v590i9lk/cryptoauthlib/lib', '-DATCA_HAL_KIT_HID=ON', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-wheel-v590i9lk/cryptoauthlib/build/lib.linux-armv7l-3.5/cryptoauthlib', '-DATCA_HAL_I2C=ON', '-DATCACERT_DEF_SRC=atca_utils_sizes.c']' returned non-zero exit status 1
```
