### ISSUE TITLE
Missing 1.16.* version of grpcio package

### ISSUE THREAD

**Issue by dmitriykovalev** [bennuttall/piwheels#104]
Missing package
Package name: `grpcio`
Link to PyPI page: https://pypi.org/project/grpcio/
Link to piwheels page: https://piwheels.org/simple/grpcio/
Version: e.g. `1.16.*`

PyPi already has several `1.16.*` packages but the latest one available on piwheels is `1.15.0`.

**Comment by bennuttall** [comment]
Thanks for the update - I build these manually, and I don't have any way of keeping up with new releases. I've kicked them off now, but they take a little while.

**Comment by bennuttall** [comment]
Done!

**Comment by dmitriykovalev** [comment]
@bennuttall  Thanks!

**Comment by Iamanorange** [comment]
Sorry to bother. Package `tensorflow` and `grpcio` are out of date.
`tensorflow` 1.11 -> 1.12 (I need 1.12)
`grpcio` 1.16 -> 1.18 (doesn't matter, just report)

**Comment by bennuttall** [comment]
Ok thanks for reporting, I'll get on to the TF team for new wheels, and I'll rebuild the latest grpcio.

**Comment by Iamanorange** [comment]
The tensorflow==1.11 in piwheels seems broken accroding to https://github.com/tensorflow/tensorflow/issues/23082 .

And tensorflow==1.11 in https://github.com/PINTO0309/Tensorflow-bin works fine.
