### ISSUE TITLE
Missing package: ruamel.yaml

### ISSUE THREAD

**Issue by fabaff** [bennuttall/piwheels#109]
Package name: `ruamel.yaml`
Link to PyPI page: https://pypi.org/project/ruamel.yaml/
Link to piwheels page: https://www.piwheels.org/simple/ruamel.yaml/
Version: `0.15.80`

**Comment by bennuttall** [comment]
Looks like source distribution wasn't uploaded when we attempted to build it - we fixed it so that won't happen in future. But anyway, I've just rebuilt it - thanks for letting us know :+1:

**Comment by fabaff** [comment]
@bennuttall, thanks for the super quick reaction to the issue.
