### ISSUE TITLE
OpenCV install issue on Raspberry Pi

### ISSUE THREAD

**Issue by kamangir** [bennuttall/piwheels#111]
Broken package
Package name: `opencv-contrib-python`
Link to PyPI page: https://pypi.org/project/opencv-contrib-python/
Link to piwheels page: https://www.piwheels.org/simple/opencv-contrib-python/
Version: e.g. `3.4.4.19`
More information:

Please use code blocks where appropriate:

I am trying to install OpenCV on a Raspberry Pi 3B. Execute the following command:
```bash
sudo pip3 install opencv-contrib-python
```
Here is what I get:
```
Collecting opencv-contrib-python
  Using cached https://www.piwheels.org/simple/opencv-contrib-python/opencv_contrib_python-3.4.3.18-cp35-cp35m-linux_armv7l.whl
Requirement already satisfied: numpy>=1.12.1 in /usr/lib/python3/dist-packages (from opencv-contrib-python)
Installing collected packages: opencv-contrib-python
Successfully installed opencv-contrib-python-3.4.3.18
```
Then I open Python3 and type in "import cv2":
```
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/cv2/__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: libjasper.so.1: cannot open shared object file: No such file or directory
```
I do a bit of Googling and find this link:
https://github.com/evancohen/sonus/issues/54
which suggests:
`sudo apt-get install libatlas-base-dev
`
Still, I receive an error message on "import cv2".

**Comment by bennuttall** [comment]
Please observe the dependencies given here: https://blog.piwheels.org/new-opencv-builds/

Fully explained here: https://blog.piwheels.org/how-to-work-out-the-missing-dependencies-for-a-python-package/

Let us know if that resolves your issue

**Comment by kamangir** [comment]
Thank you. I followed the instructions and solved the problem. Here are the commands that made it work for me.
````
sudo pip3 install opencv-contrib-python
sudo apt install libjasper1
sudo apt-get --yes --force-yes install libatlas-base-dev
````

Thank you for the help. @bennuttall

**Comment by kamangir** [comment]
Thank you. I followed the instructions and solved the problem. Here are the commands that made it work for me.
````
sudo pip3 install opencv-contrib-python
sudo apt install libjasper1
sudo apt-get --yes --force-yes install libatlas-base-dev
````

Thank you for the help. @bennuttall
