### ISSUE TITLE
Broken package: paho-mqtt

### ISSUE THREAD

**Issue by ComputerSmiths** [bennuttall/piwheels#123]
```
ImportError: No module named paho.mqtt.client
```

If I install paho-mqtt via pip, my Raspberry Pi (Debian 9.6, all up to date) grabs the piwheels.org version, which throws the error above.

If I install it from source as per https://pypi.org/project/paho-mqtt/ then it works fine.

**Comment by ComputerSmiths** [comment]
Sorry, cut and paste from another attempt to post the issue.

Raspian 9.6 all up to date.

**Comment by bennuttall** [comment]
It works fine for me on Raspbian.

Where are you getting "9.6" from? My `cat /etc/os-release` shows "9" only.

Are you using Raspbian from raspbian.org or from raspberrypi.org?

**Comment by ComputerSmiths** [comment]
cat /etc/debian_version 
9.6
Raspberrypi.org
I built it up originally using NOOBS Lite 2.8 on Sept 14, 2018
Selected Full Desktop Raspian
which was apparently 9.4
then last week did:
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade

But I've tried:
pip install paho-mqtt
on a couple of other Raspberry Pis (9.4 and 9.6) and they work just fine, so whatever the problem is it's probably specific to that particular RPi, so go ahead and close the issue as PEBKAC.  8*)

Sorry to have bothered you, and thanks again for all you do for us!

**Comment by bennuttall** [comment]
Weird - ok thanks for the update :+1:
