### ISSUE TITLE
Missing package: av

### ISSUE THREAD

**Issue by jlaine** [bennuttall/piwheels#125]
Missing package
Package name: `av`
Link to PyPI page: https://pypi.org/project/av/
Link to piwheels page: https://www.piwheels.org/simple/av/
Version: `all`
More information:

PyAV is a wrapper around the FFmpeg libraries. Debian/stretch's version of FFmpeg (3.2.x) is recent enough to build PyAV so building for the Pi *should* just work, provided the following packages are installed:

- libavformat-dev
- libavcodec-dev
- libavdevice-dev
- libavfilter-dev
- libavutil-dev
- libswscale-dev
- libswresample-dev

If you have any logs for build failures I'd be happy to help investigate.

**Comment by bennuttall** [comment]
Thanks for the report. Here's the output: http://paste.debian.net/1061525/

**Comment by bennuttall** [comment]
I've built successfully on a Stretch Pi here. `libswresample-dev` isn't a package on Jessie, so just looking into that.

**Comment by jlaine** [comment]
Concerning libswresample-dev I think you can omit it as libavcodec-dev depends on it:

https://packages.debian.org/stretch/libavcodec-dev

**Comment by bennuttall** [comment]
Done - v6.1.0 is now available for cp35. The older versions are queued up.
