### ISSUE TITLE
Build recorded but not transferred (leads to 404)

### ISSUE THREAD

**Issue by lissyx** [bennuttall/piwheels#127]
Broken package
Package name: `numpy`
Link to PyPI page: https://pypi.org/project/numpy
Link to piwheels page: https://www.piwheels.org/simple/numpy
Version: 1.16.1
More information:

One can see the package listed in https://www.piwheels.org/simple/numpy/ but the link https://www.piwheels.org/simple/numpy/numpy-1.16.1-cp34-cp34m-linux_armv7l.whl#sha256=5be2ea06bbfdabf81cb005df35206fa98ad6f3b99ad1088317e049d2596a6cfb returns 404.

**Comment by lissyx** [comment]
It looks like the armv6 wheel is also suffering from that. Given the 1.16.1 rc is here, is it just a failure during upload?

**Comment by bennuttall** [comment]
We've been having some networking issues in the datacentre. I've removed that build from the system now so it won't 404 - however you'll have to wait for the issues to get sorted out before you can get that particular wheel from piwheels.

Note: there is a bug in that this shouldn't be possible. Assigning @waveform80.

**Comment by lissyx** [comment]
Perfect, refreshing the index I don't see the broken link anymore !
Thanks !

**Comment by bennuttall** [comment]
@waveform80 is this an issue that will have been fixed with recent updates?
