### ISSUE TITLE
Missing package: scipy for Python >= 3.6

### ISSUE THREAD

**Issue by herrkaefer** [bennuttall/piwheels#130]
Missing package
Package name: `scipy`
Link to PyPI page: https://pypi.org/project/scipy
Link to piwheels page: https://www.piwheels.org/simple/scipy
Version: e.g. `1.2.1`
More information:
Python version >= 3.6

**Comment by bennuttall** [comment]
We don't generally have Python >=3.6 wheels. We'll start on 3.7 soon with some Buster builders.
