### ISSUE TITLE
Remove packages when they're removed from PyPI

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#135]
It would be good if we could eliminate packages which have been removed from PyPI to stop them showing up in search results, and to stop us actually hosting stuff which has been removed from PyPI, including spammy or malicious package names e.g. [1-800...](https://www.piwheels.org/project/1-800.-.681.-7208_EPSON_Printer_Customer_Help_Desk_Phone_Number/) and [requirements.txt](https://www.piwheels.org/project/requirements.txt/)

**Comment by waveform80** [comment]
Related to #166
