### ISSUE TITLE
pip configuration

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#14]
We need to find a way of providing instructions to configure pip to use piwheels as an additional index in a way that works for both use cases: globally and in a virtualenv.

The [user guide](https://pip.pypa.io/en/stable/user_guide/#configuration) suggests:

> Per user:
> On Unix the default configuration file is: `$HOME/.config/pip/pip.conf`

> Inside a virtualenv:
> On Unix and macOS the file is `$VIRTUAL_ENV/pip.conf`

> Site-wide:
> On Unix the file may be located in `/etc/pip.conf`

**Comment by bennuttall** [comment]
Looking at where pip gets its config file location in `locations.py` in the pip module:

```python
default_storage_dir = os.path.join(user_dir, '.pip')
default_config_file = os.path.join(default_storage_dir, 'pip.conf')
```

This is `/home/pi/.pip/pip.conf` for the pi user in a virtualenv and `/root/.pip/pip.conf`for the root user (i.e. when installing with `sudo`). I don't see how `/etc/pip.conf` comes into it.

**Comment by bennuttall** [comment]
Setting environment variables doesn't work for me either:

```bash
$ sudo su
$ export PIP_EXTRA_INDEX_URL=https://www.piwheels.hostedpi.com/simple
$ pip3 install cffi
... fetches from pypi ...
```

The same for `PIP_CONFIG_FILE=/etc/pip.conf`.

**Comment by bennuttall** [comment]
So unless we uncover something else, putting the config option in both `/root/.pip/pip.conf` and `/home/pi/.pip/pip.conf` (or the skel equivalent) will be required.

@XECDesign would something like this be possible in the default Raspbian image?

**Comment by XECDesign** [comment]
looking at strace output on stretch, I see it checking for /etc/xdg/pip/pip.conf, /etc/pip.conf, so the system-wide settings should work.

**Comment by waveform80** [comment]
I'm afraid this seems to be something that's changed over time in pip (like so many other things). Here's the relevant chunk in pip's current code: https://github.com/pypa/pip/blob/master/pip/utils/appdirs.py#L148 - I wonder if there's a path that works in 1.5.6 (the current version in jessie) and whatever version is in stretch (presumably 8.x or 9.x).

**Comment by bennuttall** [comment]
Ok there was some confusion over this, but I've now got my head around it.

On Jessie:

- You have pip 1.5.6 to start (this doesn't look at `/etc/pip.conf`)
- You can upgrade this to 9.0.1 using `sudo pip3 install pip --upgrade`
- However, if you launch a virtualenv, the pip in there is still 1.5.6
- Therefore, you have to upgrade pip again, within the virtualenv with `pip install pip --upgrade`

On Stretch:

- You have pip 9.0.1 to start (this looks at `/etc/pip.conf`)
- Therefore, without further configuration, pip inside or outside a virtualenv will respect `/etc/pip.conf`

**Comment by bennuttall** [comment]
So for users, the instructions are:

**Jessie**

System-wide installs:

1. Set `/etc/pip.conf`
1. Upgrade pip with `sudo pip3 install pip --upgrade`
1. `sudo pip3 install cffi` (fetches from piwheels)

virtualenv installs:

1. Set `/etc/pip.conf`
1. Launch virtualenv
1. Upgrade pip with `pip install pip --upgrade` (for each new virtualenv)
1. `pip install cffi` (fetches from piwheels)

**Stretch**

System-wide installs:

1. Set `/etc/pip.conf`
1. Launch virtualenv
1. `pip install cffi` (fetches from piwheels)

virtualenv installs:

1. Set `/etc/pip.conf`
1. `sudo pip3 install cffi` (fetches from piwheels)

**Comment by bennuttall** [comment]
@waveform80 I guess we just need to make this clear in our user docs, perhaps it needs its own page.

**Comment by bennuttall** [comment]
Sorry - done!
