### ISSUE TITLE
pywavefront package issue on piwheeels

### ISSUE THREAD

**Issue by einarf** [bennuttall/piwheels#142]
When installing pywavefront with `pip install pywavefront` using python 2 the piwheels index will return `https://www.piwheels.org/simple/pywavefront/PyWavefront-1.0.0-py2.py3-none-any.whl`

This version was indeed uploaded to PyPI, but was unlisted because the release was incorrectly built (It should have been a py3 only version). See: https://pypi.org/project/PyWavefront/#history

When using pip to install pywavefront on win/linux/osx using python2 and PyPI as the index version 0.4.2 is correctly installed.

Pi
```
pi@openplotter:~$ sudo pip install pywavefront 
Collecting pywavefront Using cached https://www.piwheels.org/simple/pywavefront/PyWavefront-1.0.0-py2.py3-none-any.whl 
Installing collected packages: pywavefront Successfully installed pywavefront-1.0.0
```

Linux (py2)
```
$ pip install pywavefront
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pywavefront
  Downloading https://files.pythonhosted.org/packages/f0/a3/6ca004f861af7775dd666ea1fc537a1ce90f2ae5afeac5525eb7e43a29d9/PyWavefront-0.4.2-py2.py3-none-any.whl
Installing collected packages: pywavefront
Successfully installed pywavefront-0.4.2
```

Is this a bug with pip or directly related to piwheels index? Currently python 2 users will now get a py3 package version installed when not specifying version 0.4.2 version explicitly causing a lot of confusion.

**Comment by seandepagnier** [comment]
I have upgraded pip from 9.0.1 (what was in apt-install python-pip) to pip 19.0.3, and now the correct version of the package is installed.

**Comment by bennuttall** [comment]
Please use the broken package issue template in future.

We have removed the 1.0.0 release from piwheels.org.

**Comment by einarf** [comment]
Thank you @bennuttall for resolving this amazingly quick and thank you @seandepagnier for reporting the issue 😄

**Comment by einarf** [comment]
@bennuttall Maybe linking to https://github.com/bennuttall/piwheels/issues/new/choose from the faq (https://www.piwheels.org/faq.html) could be a good idea? The link from your faq just bypassed the templates completely so I was unaware of them.

**Comment by bennuttall** [comment]
Ah, all the other "open an issue" links on the FAQ page do link to a specific template do, but the "remove a package" link doesn't. Perhaps the "Broken package" template should be more generic to include general issues, or the default issue should be a template including the info in the templates. Thanks for observing.
