### ISSUE TITLE
opencv-python - Optimized version for pi

### ISSUE THREAD

**Issue by conor-f** [bennuttall/piwheels#151]
Missing package
Package name: opencv-python
Link to PyPI page: https://pypi.org/project/opencv-python/
Link to piwheels page: https://www.piwheels.org/project/opencv-python/
Version: >4.0
Python version: 3.5/all

More information:

There is a huge advantage to more modern versions of opencv. It could also be built with NEON and FVPV3 if the current versions aren't already? The advantages are laid out in better detail [here](https://www.pyimagesearch.com/2017/10/09/optimizing-opencv-on-the-raspberry-pi/).

**Comment by bennuttall** [comment]
The ones we have currently are optimised (the armv7l ones are, the armv6l ones aren't). See build scripts here: https://gist.github.com/waveform80/3e6130ccae83012fdcd78c8f082b90ae

v4.x wheels are under way.

**Comment by conor-f** [comment]
Thanks! Any idea when or how I could track progress?

**Comment by bennuttall** [comment]
Closing in favour of #172
