### ISSUE TITLE
Missing package: opencv-contrib-python-headless

### ISSUE THREAD

**Issue by RealOrangeOne** [bennuttall/piwheels#152]
Missing package
Package name: opencv-contrib-python-headless
Link to PyPI page: https://pypi.org/project/opencv-contrib-python-headless
Link to piwheels page: https://www.piwheels.org/project/opencv-contrib-python-headless
Version: > 4
Python version: > 3.5
More information:

There are versions of `opencv-contrib-python-headless` v3, but not v4. This is also applicable for `opencv-contrib-python`.

**Comment by bennuttall** [comment]
Tricky to build, we're working on it. See other [opencv issues](https://github.com/bennuttall/piwheels/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+opencv)

**Comment by bennuttall** [comment]
Closing in favour of #172
