### ISSUE TITLE
pip install opencv-python gives error on Raspbian

### ISSUE THREAD

**Issue by bwanaaa** [bennuttall/piwheels#162]
Expected behaviour
pip install opencv-python followed by a successful installation

Actual behaviour
Gives the following error message

Collecting opencv-python
ERROR: Could not find a version that satisfies the requirement opencv-python (from version: none)
ERROR: No matching distribution found for opencv-python

I've tried pip install opencv-contrib-python, python3 -m pip install opencv-python and that gives me the same error.
And pip install --upgrade pip before trying to install opencv, but it says I already have the latest version.

Steps to reproduce
I run the commands described above in a Raspberry Pi 3 B+ with Raspbian installed.

The versions are:
Raspbian stretch lite image dated April 2019 from official website.
https://www.raspberrypi.org/downloads/raspbian/

$uname -a
Linux raspberrypi 4.14.98-v7+

$cat /etc/os-release
"Raspbian GNU/Linux 9 (stretch)"

$ python --version
Python 2.7.13

$ python3 --version
Python 3.5.3

$ pip --version
pip 19.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)

$pip search opencv-contrib-python
opencv-contrib-python (4.1.0.25)

**Comment by bennuttall** [comment]
Please use an appropriate [issue template](https://github.com/bennuttall/piwheels/issues/new/choose)

You've listed various details which indicate you're using three different python versions, and two different package names.

- We have opencv-python, opencv-python-headless, opencv-contrib-python, opencv-contrib-python-headless up to v3.4.4.19 for Python 3.4 and 3.5.

- We don't have any packages for Python 2.7.

-  We only support system 3 Python in Jessie (3.4) and Stretch (3.5) - and soon Buster (3.7).

You have installed Python 3.6 on Raspbian Stretch and you're expecting everything to still work. There's no point saying "Raspbian stretch lite image dated April 2019 from official website" if you've then replaced system Python with something else.

To install opencv on Raspbian Stretch:

```
sudo apt install libatlas3-base libwebp6 libtiff5 libjasper1 libilmbase12 libopenexr22 libilmbase12 libgstreamer1.0-0 libavcodec57 libavformat57 libavutil55 libswscale4 libqtgui4 libqt4-test libqtcore4
sudo pip3 install opencv-python==3.4.4.19
```

More info here: https://blog.piwheels.org/new-opencv-builds/
