### ISSUE TITLE
mising package opencv-python

### ISSUE THREAD

**Issue by jainthedestroyer** [bennuttall/piwheels#169]
Package name: example
Issue type: Missing package
Link to PyPI page: https://pypi.org/project/example
Link to piwheels page: https://www.piwheels.org/project/example
Version: e.g. 1.2.3 or all
Python version: 3.7.3
More information:

Installing packages on raspbian buster are very clumsy...
opencv-python is not present for installation...

**Comment by bennuttall** [comment]
Closing in favour of #172

**Comment by sdevane** [comment]
> 
> 
> Package name: example
> Issue type: Missing package
> Link to PyPI page: https://pypi.org/project/example
> Link to piwheels page: https://www.piwheels.org/project/example
> Version: e.g. 1.2.3 or all
> Python version: 3.7.3
> More information:
> 
> Installing packages on raspbian buster are very clumsy...
> opencv-python is not present for installation...

How to install this on raspberry pi? - its not found "No matching distribution found for opencv-python"

**Comment by sdevane** [comment]
Not able to install this on rasbian Buster "No matching distribution found for opencv-python"

**Comment by bennuttall** [comment]
See issue #172
