### ISSUE TITLE
Consider tracking manually added wheels

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#19]
It would be handy if we could manually add wheels for certain packages, so that we can provide wheels for packages without an sdist, but we have a wheel available, like @samjabrahams's tensorflow: https://github.com/samjabrahams/tensorflow-on-raspberry-pi

**Comment by bennuttall** [comment]
Also [pyqt5](https://pypi.python.org/pypi/PyQt5)!

**Comment by waveform80** [comment]
Implemented in 0926b47d2ceef34701e2e0c90a05c0a62f438d40..5a86b9bf51312142b6b5a7bda455d69cda948f52

**Comment by bennuttall** [comment]
/Great. How do we provide them?

**Comment by waveform80** [comment]
Just use the `piw-import` tool on the master, i.e. upload a wheel you want to import to the master, then just run `piw-import mypackage-0.0.1-someabi-somearch.whl`. By default it'll figure out the package name, version, ABI, etc. from the file but there's command line switches if you want to customize things like the build log, duration, etc (the defaults are all quite "dumb"; the duration defaults to nothing and the build log to some boring "imported" message). The tool should import the wheel into the database as if it were a "normal" build, copy it to the relevant dir on the file-system and generate the necessary index.

Full docs over here: http://piwheels.readthedocs.io/en/latest/importer.html

**Comment by bennuttall** [comment]
Ooh very nice

**Comment by bennuttall** [comment]
I've imported a few tensorflow releases from @samjabrahams's github project https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases

But note these are built for Python 2.7 and 3.4, not 3.5, and do not include the last few releases (latest available is 1.1.0 when the actual latest release is 1.4.0).

I'll look into the build process and see if we can get them built ourselves in future.

**Comment by waveform80** [comment]
How on earth did you import the 2.7 wheels? I thought I'd banned the importer from being able to import stuff with an ABI that wasn't set as buildable?

**Comment by bennuttall** [comment]
Apparently not! Although after I realised what I'd done, I had a look in the database, and couldn't find trace of any Python 2 builds. Perhaps it transferred them but didn't log them in the database?
