### ISSUE TITLE
Missing package: mysqlclient

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#22]
Package: [mysqlclient](https://pypi.python.org/pypi/mysqlclient)
Reason for failure: missing build dependencies `libmysqlclient-dev` (jessie) or `libmariadbclient-dev` (stretch)

**Comment by waveform80** [comment]
This should now build over the next few hours - do feel free to re-open if you find anything wrong with the package (or if it  doesn't show up in the next couple of hours or so).

**Comment by bennuttall** [comment]
Got it - thanks

@topshed did you request this?

**Comment by topshed** [comment]
No - but a weather station user did flag it on the forum
