### ISSUE TITLE
504 Gateway Time-out for the repository

### ISSUE THREAD

**Issue by lyw07** [bennuttall/piwheels#24]
I'm not able to connect to the repository: www.piwheels.hostedpi.com. It was working fine about several minutes ago, but then I'm not able to connect to it anymore. Could anyone help with this? Thank you so much!!

**Comment by waveform80** [comment]
It's working for me at the moment, but it's possible something may have been up with Mythic's forwarding gateway earlier (there was some [planned maintenance](http://status.mythic-beasts.com/) on a hosting server last night but I think that was a bit earlier on around 23:00 UTC).

The Pis that Mythic hosts (which piwheels runs on) aren't directly accessible from IPv4 (they've only got IPv6 addresses) so there's a gateway that forwards certain traffic (like SSH and HTTP) from IPv4 to them. If it's still down for you then that suggests there's another gateway between you and Mythic which is having a problem.

**Comment by waveform80** [comment]
Dug into this a bit further - it does seem there was something that affected the main piwheels server at some point last night but it resolved itself (as far as the web hosting is concerned at least).

I have had to restart the build slaves as they lost connection to the main server at some point (and there's no reliability in the protocol at the moment - it's all very basic). The root issue was that the main server (the one that hosts the files and provides access via the web) lost connection to its NFS server. As the NFS server hosts its root file-system that caused it some issues! Anyway, it came back online a while later, Apache got back on its feet and all was well. I've thrown in some extra monitoring on the main server but that's about all we can do for now (at the moment this is all a volunteer service - even the hosting is being generously donated by Mythic).

**Comment by lyw07** [comment]
Thank you! It's working for me now.
