### ISSUE TITLE
New homepage content

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#26]
Related to #21, here's a new overview for the homepage:

---

# Python Wheels for the Raspberry Pi

piwheels is a Python package repository providing ARM platform wheels (pre-compiled binary Python packages) specifically for the Raspberry Pi. Packages are natively compiled on Raspberry Pi 3 hardware using the [Mythic Beasts Pi cloud](https://www.mythic-beasts.com/order/rpi).

> Packages: 105,885
> Versions: 766, 450

## Configuration

[Raspbian Stretch](https://www.raspberrypi.org/downloads/raspbian/) includes configuration for pip to use piwheels by default. If you're using an alternate distribution, you can use piwheels by placing the following lines in `/etc/pip.conf`:

```
[global]
extra-index-url=https://www.piwheels.hostedpi.com/simple
```

That's it! With this simple configuration change, pip should now search piwheels for built distributions of packages and use them in preference to building from source. You can test this out by creating a virtual environment and attempting to install [numpy](http://www.numpy.org/) which usually involves a fairly lengthy compilation:

```
$ sudo apt install virtualenv python3-virtualenv -y
$ virtualenv -p /usr/bin/python3 testpip
$ source testpip/bin/activate
(testpip) $ pip install numpy
...
(testpip) $ deactivate
$ rm -rf testpip/
```

## Support

Wheels provided support all Raspberry Pi models (Pi 3, Pi 2, Pi 1 and Pi Zero). Wheels are provided for Python 3.4 and 3.5. We plan to add support for Python 3.6 and 2.7.

## About

piwheels is a community project by [Ben Nuttall](https://github.com/bennuttall) and [Dave Jones](https://github.com/waveform80). Hosting kindly provided by [Mythic Beasts](https://www.mythic-beasts.com/). See the project source code on [GitHub](https://github.com/bennuttall/piwheels) and read more about the service in our [FAQs](https://www.piwheels.hostedpi.com/faqs.html).

---

**Comment by waveform80** [comment]
New homepage in production; still need to redo the stats view but that's a DB structure change so I'm holding off for a bit until I can fit some more in. On adding Mythic's logo to the homepage, can you have a quick check if there's any guidelines to follow there? (size, placement, what it has to link to, blah blah).

**Comment by bennuttall** [comment]
Just waiting on that!
