### ISSUE TITLE
Re-attempt failed packages for higher ABIs

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#29]
Currently we only rebuild packages successfully built for 3.4 for 3.5, but that's excluding any packages which depend on Python 3.5 features. I can't think of another way around it, but I guess we'll have to re-attempt all failed builds for Python 3.5 (and 3.6).

This means the current build queue logic (multiply ABIs and successful builds) means we also need to include failed builds. We don't need to re-attempt successful builds with an ABI of `none`, but we need to rebuild those with a lower ABI (e.g. `cp34m`) and re-attempt failed builds, in case they are dependent on the current higher ABI (e.g. `cp3.535m`).

**Comment by waveform80** [comment]
Fixed in 0.9
