### ISSUE TITLE
Developer documentation

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#3]
I should aim to provide developer setup instructions so people can git clone this repo, run a set of commands and have a working copy of piwheels ready to use for testing, initially on a Pi, later on any platform.

**Comment by bennuttall** [comment]
Merged into master but a wip!

**Comment by lurch** [comment]
Purely out of curiosity - why do you list `gpiozero` as a requirement in the instructions?

**Comment by bennuttall** [comment]
It's a requirement of the test suite (so for developing - but not necessarily setting installing - I will remove from there). In the tests I use `PingServer` to check whether a connection to PyPI can be made before proceeding, so that if I'm developing offline I can run the tests with a "PyPI tests skipped" warning rather than an error. See https://github.com/bennuttall/piwheels/blob/master/piwheels/tests.py#L62

**Comment by lurch** [comment]
Ahh, seems like a bit overkill, but fair enough ;-)

**Comment by bennuttall** [comment]
This is on hold until I merge some changes @waveform80 has been working on.

**Comment by waveform80** [comment]
I've started documenting various classes and methods (and included some pretty diagrams of things like the protocols between the master and slaves, and the queues used within the system) but there's still plenty to be done.

**Comment by bennuttall** [comment]
Docs are comprehensive and have been published at http://piwheels.readthedocs.io/

@waveform80 happy to close this?

**Comment by waveform80** [comment]
Yup - they're as good as I've got time for right now :)
