### ISSUE TITLE
Provide a browsable version of project pages

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#33]
We should provide an HTML page for every package, intended for users to browse packages on the piwheels website, akin to the browsable package index on PyPI: e.g. https://pypi.python.org/pypi/numpy

We would provide package pages at `/piwheels/<package>` (unless anyone has a better suggestion).

I imagine the process to generate pages would be alongside where we currently generate the links page in `/simple/<package>`.

Based on a template (using the homepage style), this could include a list of versions, and maybe something like checkboxes for which builds we have (python version / etc). Bit tricky due to some being "none", others being py3, others being cp34m.

I have started work on the template and I will try to get a basic version working...

**Comment by waveform80** [comment]
Couple of hints on getting it working:

The easiest place to bung the logic will be in the [index scribe task](http://piwheels.readthedocs.io/en/latest/master.html#index-scribe) probably alongside the method which handles writing the simple index. You may need to enhance the output of the method which gathers info on the available files (that'll be initially in the db module, and then in the oracle module which uses it).

**Comment by bennuttall** [comment]
Would make sense to follow warehouse and provide project pages at `/project/numpy`: https://pypi.org/project/numpy/

**Comment by bennuttall** [comment]
This is mostly complete, pending some style changes I'll track here:

- Versions table
  - [ ] describe builds column as successful / unsuccessful
  - [ ] cap number of files to show (with javascript opener)

- Files table
  - [ ] show "no files" message rather than empty table
  - [ ] cap number of files to show (with javascript opener)
  - [ ] filesize should be human readable not bytes

**Comment by bennuttall** [comment]
![screenshot from 2019-01-13 17-35-45](https://user-images.githubusercontent.com/1609725/51088661-4c883080-175a-11e9-9ee1-1b733d62ec4b.png)

![screenshot from 2019-01-13 17-36-01](https://user-images.githubusercontent.com/1609725/51088663-501bb780-175a-11e9-8fc4-3f09bcc1661d.png)

**Comment by bennuttall** [comment]
Getting there:

![screenshot from 2019-01-13 18-06-12](https://user-images.githubusercontent.com/1609725/51088961-fd43ff00-175d-11e9-8e14-a7afa76c9498.png)

**Comment by bennuttall** [comment]
I wonder if it would be possible to show more useful information in successful / unsuccessful builds, like:

```
Successful  | Unsuccessful
cp34m cp35m | cp36m
```

That would be more useful and would remove ambiguity from duplicates (I think if two builders attempt to build the same package it would show twice).

**Comment by bennuttall** [comment]
Also "skip" isn't clear when they're null. I almost want to see a tick if it's not skipped, but the header would have to be something else.

**Comment by bennuttall** [comment]
I've changed the order to be newest first - as I will next reduce the table and only show the first few my default, they ought to be the latest ones.

**Comment by bennuttall** [comment]
This too:

![screenshot from 2019-01-13 17-35-45](https://user-images.githubusercontent.com/1609725/51089759-6f224580-176a-11e9-92d6-d3236547ff29.png)

**Comment by bennuttall** [comment]
I've finished the bulk of presentation improvements in 3cbdbed844e9a601f82c1d18f3adf19500c0692f

Only show latest 5 versions and files by default:

![screenshot from 2019-01-13 23-54-31](https://user-images.githubusercontent.com/1609725/51092495-e74f3200-178f-11e9-88ff-2da3eb2210fc.png)

Allow opening the rest with a click:

![screenshot from 2019-01-13 23-54-43](https://user-images.githubusercontent.com/1609725/51092505-ffbf4c80-178f-11e9-8f28-b123249a4dde.png)

Still got to sort out the "skip" column, and I've optimistically added download stats to project pages - @waveform80 can we afford to do that?

**Comment by bennuttall** [comment]
Deployed
