### ISSUE TITLE
Missing package: pybluez

### ISSUE THREAD

**Issue by mishas** [bennuttall/piwheels#34]
Package: [pybluez](https://pypi.python.org/pypi/PyBluez)
Reason for failure: missing build dependencies `libbluetooth-dev `.

**Comment by waveform80** [comment]
This should now build over the next few hours - do feel free to re-open if you find anything wrong with the package (or if it  doesn't show up in the next couple of hours or so).

**Comment by mishas** [comment]
Please note that the pybluez package was not build :(
Here's the (empty) directory on piwheels: https://www.piwheels.hostedpi.com/simple/pybluez/

Is there a way to get the build error log to understand what's missing?
On my setup, it seems to build just fine (although my setup is not 1-to-1 to yours).

Thank you.

**Comment by waveform80** [comment]
> Is there a way to get the build error log to understand what's missing?

Yes, but not publicly (yet - this is planned in #16). I'll take a look in a mo.

**Comment by waveform80** [comment]
Well this is bizarre. The error is:

```
...
   In file included from bluez/btmodule.c:20:0:                                                                       
   bluez/btmodule.h:5:33: fatal error: bluetooth/bluetooth.h: No such file or directory                               
    #include <bluetooth/bluetooth.h>                                                                                  
                                    ^                                                                                 
   compilation terminated.                                                                                            
...
```

But I was sure I installed libbluetooth-dev ... I'll re-open this while I investigate further ...

**Comment by waveform80** [comment]
Oh, I'm an idiot - should've looked at the `built_at` field! I installed the deps but haven't wiped the failed builds from the database (must've forgotten it in the delete statement) so it hasn't retried them yet. Just a mo ...

**Comment by waveform80** [comment]
Right, all done now :) Many thanks for checking!
