### ISSUE TITLE
HTTP(S) service unavailable

### ISSUE THREAD

**Issue by djchen** [bennuttall/piwheels#37]
www.piwheels.hostedpi.com seems to be down.
Confirmed with http://downforeveryoneorjustme.com/www.piwheels.hostedpi.com and Pingdom.

**Comment by dzielin** [comment]
I'm seeing the same thing.  It seems there was a similar issue (#36) about a week ago.

**Comment by tweirtx** [comment]
Can confirm, unable to install a package on my Pi with an error of timeouts to this site

**Comment by dzielin** [comment]
If you need to install things in the meantime, you can use https://pypi.python.org/.  You can use `pip3 install URL` with either the wheel or the .tar.gz from pypi directly.

**Comment by waveform80** [comment]
Seems like Mythic's NFS server had some issue last night (woke up to a pile of ping-failed texts). Unfortunately with the master's swap on NFS (it can't be anywhere else as the only storage the cloud Pis have is NFS) such hiccups typically prove fatal. I'll have a chat with Ben and see if he can dig up some more info. In the meantime, I've restarted the master so everything's back up and running again.

**Comment by djchen** [comment]
Thanks @waveform80
