### ISSUE TITLE
Remove package from PiWheels

### ISSUE THREAD

**Issue by adammhaile** [bennuttall/piwheels#38]
I do love what you are doing with PiWheels but I would really like to blacklist one my packages from being built and provided by it.
For one, mine are pure python so there's absolutely no need.
Second, one of my packages [BiblioPixelAnimations](https://pypi.python.org/pypi/BiblioPixelAnimations) is a little weird in the way it builds. The version is just a timestamp of when my travis instance builds the package. But by PiWheels rebuilding that the version gets changed. And from what I can tell, the latest version it has is even a *very* old version of the code...the very old Python 2.7 only version. Can't tell you why but I know it is. All of my users on the Pi have suddenly begun complaining that their code is crashing and I've noticed that all the complaints are coming from those who have the package installed from PiWheels.
In the future maybe they can be added back but right now I have an immediate need for them to be removed ASAP so that my users can get back up and running and take the time to triage why there was a problem later.
Thanks

**Comment by waveform80** [comment]
Sure, no prob - I've set it to skip at the package level so no new releases will be built and I've wiped the existing builds from the server.

On the subject of building very old instances: piwheels uses PyPI's XML-RPC API to replay PyPI's event log (it's much more efficient and friendlier to PyPI's bandwidth than scraping all the PyPI packages individually). However, this does means it effectively picks up the package's first registration and attempts to build every version that's ever been registered (even if those versions have subsequently been deleted; that may seem mad, but there's a reason for it!).

Anyway, hopefully that'll sort things out - do let me know if anything's still broken at your end.

**Comment by adammhaile** [comment]
Ah.... that would be why. Because of my genius (at the time) method of
letting travis set the build version to the datestamp, it means that older
version of the code could have newer versions in piwheel if they were built
later.
I do still see it on the server though:
https://www.piwheels.hostedpi.com/simple/bibliopixelanimations/
Maybe it's just cached for a bit?
While we are at it, this one probably isn't as much a problem, but maybe
blacklist this as well?
https://www.piwheels.hostedpi.com/simple/bibliopixel/
Again, it's pure python so it will be of no detriment to anyone installing
it.
Thanks!

@rec - Looks like we may be ok now :)

**Comment by adammhaile** [comment]
Oh... nevermind. It wasn't empty when I looked, which is what I was getting
at, not that the link still existed. Now it's empty. So yeah, just cached
still.
Thanks!

**Comment by waveform80** [comment]
Ah, no worries - I'm not sure if the IPv6 proxy in front of piwheels does any caching, but it may well do (Mythic's cloud Pi's only have IPv6 addresses so everything sits behind a proxy which may be doing a bit of caching). 

You should shortly see that BiblioPixel is now blank too (caching notwithstanding :). If there's any further packages you need "blanked" do feel free to re-open this and let me know.

**Comment by adammhaile** [comment]
Awesome, thanks so much!
