### ISSUE TITLE
Package versions

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#4]
I'm having issues keeping track of whether or not I have the latest version of a package.

- I keep a record of what I consider the latest version number of a package in the database, and update this regularly (from PyPI's JSON API)
- I keep a record of the version of the package when I built it
- Therefore, I can deduce which packages require an update

This sounds trivial. However, the way I record the version at the point of build is to extract it from the output wheel filename. I've now come to realise that this is often inconsistent with the version recorded in PyPI.

For example:

1. Look up the version of `doxybuild` on PyPI ([JSON](https://pypi.python.org/pypi/doxybuild/json)). It's `0.1.1-alpha`.
1. Run `pip wheel doxybuild` and extract the version from the filename. It's `0.1.1_alpha`.

Again, this seems trivial, as the hyphen has been replaced with an underscore. Another example:

1. Look up the version of `Hooke` on PyPI ([JSON](https://pypi.python.org/pypi/Hooke/json)). It's `1.0.0.alpha (Ninken)`.
1. Run `pip wheel Hooke` and extract the version from the filename. It's `1.0.0.alpha._Ninken_`.

Again, seems trivial, but there are lots of similar examples, and some are more different than the above examples:

```
package | strict
version | 0.1alpha
version | 0.1a0
-[ RECORD 2 ]----------------------------
package | strippers.wikipedia
version | 0.3
version | 0.3a0
-[ RECORD 3 ]----------------------------
package | sudokulib
version | 0.6a
version | 0.6a0
-[ RECORD 4 ]----------------------------
package | sy85tools
version | 0.2.2a
version | 0.2.2a0
-[ RECORD 5 ]----------------------------
package | synchrophasor
version | 1.0.0-alpha
version | 1.0.0a0
-[ RECORD 6 ]----------------------------
package | testsuite-prettyprint-outcomes
version | 0.1.0-alpha.1
version | 0.1.0a1
-[ RECORD 7 ]----------------------------
package | testsuite-prettyprint-traceback
version | 0.1.0-alpha.2
version | 0.1.0a2
-[ RECORD 8 ]----------------------------
package | timepy
version | 0.1a
version | 0.1a0
-[ RECORD 9 ]----------------------------
package | tissu
version | 0.4-alpha
version | 0.4a0
-[ RECORD 10 ]---------------------------
package | tracticketpost
version | 0.2a6dev
version | 0.2a6.dev0
```

I need to be able to tell when a new version has been released by the version number changing. If it's expected to be different, then how can I tell?

Does anyone have any ideas for how I can/should record the version to be more consistent?

**Comment by bennuttall** [comment]
@waveform80 @lurch @ntoll @lordmauve

**Comment by ntoll** [comment]
Chatted with @bennuttall in meat-space about this. ;-)

I think we've found a solution that bypasses shonky/inconsistent version details.

**Comment by bennuttall** [comment]
release datetimes it is!

**Comment by bennuttall** [comment]
This is resolved by v2 building every version of every package :tada:
