### ISSUE TITLE
Missing package: tensorflow

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#41]
A non-trivial build. No sdist is available on PyPI.

For the time being, I have manually imported some @samjabrahams's builds from github https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases

Sam provides build instructions here: https://github.com/samjabrahams/tensorflow-on-raspberry-pi/blob/master/GUIDE.md

I'll have a go, see how I get on :)

**Comment by bennuttall** [comment]
@samjabrahams are you able to help me with this?

**Comment by samjabrahams** [comment]
@bennuttall sorry for the delay; unfortunately it's hard to find time to work on the Pi wheel repo right now. That said, the Tensorflow team has official nightly binaries available on their CI website- that may be what you need:

http://ci.tensorflow.org/view/Nightly/job/nightly-pi/

http://ci.tensorflow.org/view/Nightly/job/nightly-pi-python3/

http://ci.tensorflow.org/view/Nightly/job/nightly-pi-zero/

http://ci.tensorflow.org/view/Nightly/job/nightly-pi-zero-python3/

**Comment by bennuttall** [comment]
It's odd they have the `any` platform tag and that they provide 2.7 and 3.4 (not 3.5). I'll see if I can reach out to them.

**Comment by bennuttall** [comment]
Awaiting response from the tensorflow team https://github.com/tensorflow/tensorflow/issues/18202

**Comment by bennuttall** [comment]
I have been sent some top-of-tree tensorflow wheels and I'm currently testing them. Will update as I test each one:

*Note: link text is what the file should (and will) be named, but this differs from the actual filenames as provided*

| Python version | Arm version | File | Status |
| - | - | - | - |
| 2.7 | Armv6 | tensorflow-1.8.0-cp27-cp27mu-linux_armv6l.whl | Currently broken |
| 3.4 | Armv6 | [tensorflow-1.8.0-cp34-cp34m-linux_armv6l.whl](http://ci.tensorflow.org/view/Nightly/job/nightly-pi-python3/217/artifact/output-artifacts/tensorflow-1.8.0-cp34-none-any.whl) |  |
| 3.5 | Armv6 | [tensorflow-1.8.0-cp35-cp35m-linux_armv6l.whl](http://ci.tensorflow.org/view/Nightly/job/nightly-pi-python3/217/artifact/output-artifacts/tensorflow-1.8.0-cp34-none-any.whl) | py34 wheel renamed - seems to work but a warning is shown at import time |
| 2.7 | Armv7 | [tensorflow-1.8.0-cp27-cp27mu-linux_armv7l.whl](http://ci.tensorflow.org/view/Nightly/job/nightly-pi-zero/270/artifact/output-artifacts/tensorflow-1.8.0-cp27-none-any.whl) |  |
| 3.4 | Armv7 | [tensorflow-1.8.0-cp34-cp34m-linux_armv7l.whl](http://ci.tensorflow.org/view/Nightly/job/nightly-pi-python3/217/artifact/output-artifacts/tensorflow-1.8.0-cp34-none-any.whl) |  |
| 3.5 | Armv7 | [tensorflow-1.8.0-cp35-cp35m-linux_armv7l.whl](http://ci.tensorflow.org/view/Nightly/job/nightly-pi-python3/217/artifact/output-artifacts/tensorflow-1.8.0-cp34-none-any.whl) |  |

**Comment by bennuttall** [comment]
Warnings:

Python 3.5:
```
>>> import tensorflow
/home/pi/py3/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/home/pi/py3/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
```

**Comment by bennuttall** [comment]
This is done: tensorflow/tensorflow#18202

Woo! Thanks @petewarden

**Comment by liuqun** [comment]
Hi @bennuttall !

I got the same warnings on python 3.5 with tensorflow-1.9.0-cp35-armv7l.whl and numpy-1.14.5 installed:
```
>>> import tensorflow
/home/pi/py3/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.4 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/home/pi/py3/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: builtins.type size changed, may indicate binary incompatibility. Expected 432, got 412
  return f(*args, **kwds)
```

Any ideas on how to fix this issue?

**Comment by bennuttall** [comment]
The tensorflow wheels were built with Python 3.4 but they do work with 3.5. The TF team say they will resolve this in the next release. Note it's just a warning not an error. It still works fine.
