### ISSUE TITLE
Implement heartbeat

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#48]
It would be nice if we implemented a heartbeat signal of some sort, so that we could monitor whether piwheels was running (without logging in and seeing the master output).

It could be something simple, like a timestamp in an HTML comment at the end of the index page, or actually visible in the footer, or even something more detailed, covering all the different parts, to show which bits were active.

**Comment by waveform80** [comment]
This is now (sort of) implemented: both master and slave daemons use systemd's watchdog capabilities. If they fail to ping systemd, it'll restart them and, for the slaves, if the restart fails a certain number of times within a period, it'll forcefully reboot the slave.

I should also mention, we already had a heartbeat of sorts in the monitor system: the master's big-brother process periodically sends out statistics from the master to any subscribed monitors and this could be used as a heartbeat (although the monitor queues are currently restricted to on-machine IPC queues).
