### ISSUE TITLE
Missing package: pycurl

### ISSUE THREAD

**Issue by va1entin** [bennuttall/piwheels#49]
Firstly, thanks for the great work on piwheels! It's greatly appreciated. ❤️ 

`pycurl` is currently missing on piwheels. There is nothing at https://www.piwheels.hostedpi.com/simple/pycurl/

I noticed it because I tried to install something with a dependency on pycurl using pip and piwheels. Because there seems to be nothing there it doesn't even try to build from source.

I couldn't find a link or anything regarding logs from the piwheels cluster to determine what's going wrong, so I assume only you guys have access to that.

**Comment by bennuttall** [comment]
Thanks! It looks like you have given us everything we need. I'll check that package install works on both jessie and stretch and make sure it gets built.

**Comment by bennuttall** [comment]
It seems to be working fine. Builds are in progress:

![screenshot from 2018-02-21 18-31-01](https://user-images.githubusercontent.com/1609725/36498174-70b3431c-1735-11e8-8c2d-f7a1bc7d4d83.png)

Successful ones are appearing: https://www.piwheels.hostedpi.com/simple/pycurl/

**Comment by va1entin** [comment]
Nice! Thx for merging :+1:

**Comment by bennuttall** [comment]
Thanks for contributing! :1st_place_medal:
