### ISSUE TITLE
Missing package: pygame

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#52]
Now Pygame is available on PyPI, we are able to build it on piwheels. However, all builds have failed, and it boils down to:

```
Unable to run "sdl-config". Please make sure a development version of SDL is installed.
```

If anyone knows what the build requirements for Debian are for Pygame, please post here, we'll install and kick off the builds again.

**Comment by illume** [comment]
```
apt-get install python-dev libsdl-image1.2-dev libsdl-mixer1.2-dev \
        libsdl-ttf2.0-dev libsdl1.2-dev python-numpy libportmidi-dev libjpeg-dev \
        libtiff4-dev libx11-6 libx11-dev xfonts-base xfonts-100dpi xfonts-75dpi \
        xfonts-cyrillic fluid-soundfont-gm musescore-soundfont-gm
```

**Comment by bennuttall** [comment]
Thanks! It looks like `libtiff4` is `libtiff5` in Debian Stretch, but that's easy enough to deal with.

**Comment by bennuttall** [comment]
Actually, it's `libtiff5` in Jessie too.

**Comment by illume** [comment]
Sorry about that.

This is wonderful. Many thanks!

I haven't been following the raspberry pi world in the last several months...

Does this mean these piwheels will be available for people by default on raspbian? Or would we need to make them available on pypi somehow? Are there docs somewhere for how people can help contribute to these build scripts? Or how to generate these wheels, if we should be doing it ourselves?
```
python setup.py build
python run_tests.py
python -m pygame.tests
```

**Comment by bennuttall** [comment]
I have successfully built pygame on a Pi :+1: 

```
pygame-1.9.3-cp35-cp35m-linux_armv7l.whl
```

I'll add those dependencies to piwheels builders and get it to rebuild them all.

**Comment by illume** [comment]
Cool. So, it looks like when we do the next release we have to do... nothing. That's my favourite amount of doing.

Thanks again.

**Comment by bennuttall** [comment]
Builds are in progress and successful ones are appearing at https://www.piwheels.hostedpi.com/simple/Pygame/

**Comment by bennuttall** [comment]
Ok the only version that built successfully was the latest (1.9.3) but it successfully built for Python 3.4 and 35 (and we provide Armv6 and Armv7 versions but they are the same):

```
pygame-1.9.3-cp34-cp34m-linux_armv6l.whl
pygame-1.9.3-cp34-cp34m-linux_armv7l.whl
pygame-1.9.3-cp35-cp35m-linux_armv7l.whl
pygame-1.9.3-cp35-cp35m-linux_armv6l.whl
```

I assume the build requirements were different prior to 1.9.3 - do you care that older versions did not build successfully, or not?

**Comment by illume** [comment]
No, it's fine that older versions aren't working. This is the first version that works with wheels.

**Comment by bennuttall** [comment]
Great. I've added the build dependencies to the deploy script. All being well, when you release 1.9.4, it will be built automatically.

**Comment by waveform80** [comment]
> Does this mean these piwheels will be available for people by default on raspbian? Or would we need to make them available on pypi somehow? Are there docs somewhere for how people can help contribute to these build scripts? Or how to generate these wheels, if we should be doing it ourselves?

Just to add: I think all these questions are answered in the [FAQ](https://www.piwheels.hostedpi.com/faq.html) (buried down the bottom of the [homepage](https://www.piwheels.hostedpi.com/) because I suck at web design ;). If anything isn't, do let us know so we can add it!

**Comment by illume** [comment]
Thanks @waveform80

**Comment by bennuttall** [comment]
@illume When is the 1.9.4 release expected? :)

**Comment by illume** [comment]
Minimum of one week, likely two weeks. There will be a release candidate out soon, then a weeks wait for people to test. But it all depends on volunteers... so I guess it could go on for a month.
