### ISSUE TITLE
Add a package blacklist

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#53]
We should document which apt packages we definitely don't want installed on the slaves, like pyqt which makes subsequent matplotlib builds dependent on that also being installed for the user (but works fine if built without it, regardless of whether it's installed for the user).

It doesn't need to be part of the installation process, just documented somewhere. For example when I added those packages to fix pygame #52 and pycurl #49 I could have referred to the blacklist before adding them (risking breaking built packages in future).

**Comment by waveform80** [comment]
I'm in two minds about this; after all certain of the OpenCV packages we provide (admittedly manually) depend on Qt and I can't help but feel a proper implementation of #59 would render this unnecessary. There's also the issue that even if we document a blacklist (like "no Qt") we won't accidentally pull it in via some other package that we add as a dep.

Basically I think this would be a slightly-broken stop-gap which #59 fixes "properly".

**Comment by bennuttall** [comment]
Sure :+1:
