### ISSUE TITLE
Check XML-RPC API for warehouse

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#58]
Looks like warehouse tweaks the PyPI XML-RPC API, we'd better check and fix for it as they're moving from legacy to warehouse in the next month (and already started directing a proportion of traffic to it).

**Comment by bennuttall** [comment]
http://pyfound.blogspot.co.uk/2018/03/warehouse-all-new-pypi-is-now-in-beta.html?m=1

**Comment by brainwane** [comment]
[Here's the Warehouse roadmap](https://wiki.python.org/psf/WarehouseRoadmap) -- we plan to redirect traffic to the new codebase on Monday, 16 April, and to shut down the legacy site entirely on Monday, 30 April. And [please do file an issue](https://github.com/pypa/warehouse/issues) (including against [our API docs](https://warehouse.readthedocs.io/api-reference/)) if anything doesn't work for you!

**Comment by bennuttall** [comment]
Thanks @brainwane :+1: 

ping @waveform80

**Comment by waveform80** [comment]
Thankfully the XML-RPC mirroring methods (specifically [`changelog_since_serial`](https://github.com/bennuttall/piwheels/blob/master/piwheels/master/pypi.py#L85)) are still working; I've noticed the XML-RPC API is marked deprecated and that the JSON API is the replacement but I don't see any replacement in the JSON API for the mirroring functions. Can we assume they'll be sticking around for the foreseeable future?

**Comment by brainwane** [comment]
Question for @ewdurbin and @di I think. ^

**Comment by ewdurbin** [comment]
We haven't landed on a new design for exposing the information necessary for the mirroring infrastructure. It's safe to assume that the [methods related to mirroring](https://warehouse.readthedocs.io/api-reference/xml-rpc/#mirroring-support), specifically:

- `changelog`
- `changelog_last_serial`
- `changelog_since_serial`
- `list_packages_with_serial`

will be around until the following criteria are met:

1) A new API is designed, deployed, tested, and stabilized that supports the needs of PyPI mirrors
2) Support for new APIs is added to https://github.com/pypa/bandersnatch
3) Announcements of End-Of-Life for XMLRPC endpoints occurs

It's probably a very good idea for all users of XMLRPC (and PyPI generally) to subscribe to the low-volume distribution list pypi-announce@python.org to stay up to date on changes to PyPI.

**Comment by bennuttall** [comment]
Great, thanks.

**Comment by ewdurbin** [comment]
Link to subscribe, sorry I forgot: https://mail.python.org/mm3/mailman3/lists/pypi-announce.python.org/

**Comment by waveform80** [comment]
@ewdurbin That's good to know, thanks! Just to let you know: I'll be deploying an update to the piwheels master in a couple of weeks that changes the User-Agent in our requests to "piwheels/<version>" so you can tell us if we're ever hammering the API too much (it should be pretty gentle though - I've enforced a ten second gap between changelog requests).

**Comment by waveform80** [comment]
Okay, I'm subscribed to the `pypi-announce` list so I'll keep an eye out for future changes. For reference, the only method we actually care about is `changelog_since_serial` (it's the only method we use).

For now I'll close this ticket as the "checking" is done; if plans arise to retire (or migrate) the mirror APIs in future I'll re-open this to remind myself to do something about it :)
