### ISSUE TITLE
Store user dependencies in database

### ISSUE THREAD

**Issue by bennuttall** [bennuttall/piwheels#59]
When installing something like opencv from piwheels, it doesn't work until the user dependencies are satisfied - not pip dependencies as these are obviously covered by pip itself, but apt dependencies.

It would be good if we were able to log these in the database (could just be a text field with html - or even just assume it's all commands and stick the whole thing in a `<pre>`) and render them on the project pages (coming in #33). We'd only do it for a select few, and allow additions via github issue, no need to do more than that.

- [x] Database change
- [x] Algorithm to calculate dependencies
- [x] Enhance importer to permit manual dependency specification
- [x] Inclusion in web pages

**Comment by kitmf** [comment]
When I use pi to command with 'pip install opencv_contrib_python-3.4.0.12-cp34-cp34m-linux_armv6l.whl'
but it had a error with 'opencv_contrib_python-3.4.0.12-cp34-cp34m-linux_armv6l.whl  is not a supported wheel on this platform.'
My pi is 3,and python is 3.4

**Comment by bennuttall** [comment]
Why are you running that command? You're explicitly trying to install the armv6 wheel which is for Pi 1.

Just run `pip install opencv_contrib` and it will pick the right file for your Pi.

Also please open a new issue rather than replying to another issue.

**Comment by kitmf** [comment]
Really thanks a lot,I hava installed opencv_contrib on my pi just now.
Forgive my English is poor
