### ISSUE TITLE
Missing package: systemd-python

### ISSUE THREAD

**Issue by mashayev** [bennuttall/piwheels#61]
Package: [systemd-python](https://pypi.python.org/pypi/systemd-python)

**Comment by mashayev** [comment]
I see that this package is missing `libsystemd-dev` in https://github.com/bennuttall/piwheels/blob/master/deploy_slave.sh

**Comment by bennuttall** [comment]
Thanks for reporting this. I've added the dependency to the slave deploy script and installed on all nodes. It's now been built (all versions) and is available: https://www.piwheels.org/simple/systemd-python/
