### ISSUE TITLE
piwheels.org down

### ISSUE THREAD

**Issue by edorgeville** [bennuttall/piwheels#62]
isup.me/piwheels.org
isitdownrightnow.com/piwheels.org.html

Is there any mirror for piwheels.org ?

**Comment by scisslehannd** [comment]
How do we fix this issue?

**Comment by bennuttall** [comment]
We had some issues last week which have now been dealt with. The 'master' Pi running the web server was also hosting the piwheels database, which was occasionally going into swap, which would be fine except that we're on an NFS. We've now split the database from the web server and they're both running happily. The web server is now a dedicated Pi, and should be much more reliable.

We will likely consider a fallback server in future, in case the Pi goes down.

If ever piwheels is down, and is causing issues with pip, you can temporarily remove `/etc/pip.conf` and just use PyPI as before. Obviously you won't get Arm wheels, just sdist.
