### ISSUE TITLE
Problem with upper/lower case package names

### ISSUE THREAD

**Issue by pintman** [bennuttall/piwheels#63]
I tried to install the package RPi.GPIO which is available in the [package cache](https://www.piwheels.hostedpi.com/simple/RPi.GPIO/). Pip3.4 now tries to access the wrong lowercase URL and fails to retrieve the package.

    $ pip3.4 install -v --no-cache-dir --extra-index-url=https://piwheels.org/simple RPi.GPIO
    [...]
    Getting page https://piwheels.org/simple/rpi.gpio/
    Starting new HTTPS connection (1): piwheels.org
    "GET /simple/rpi.gpio/ HTTP/1.1" 404 295
    Could not fetch URL https://piwheels.org/simple/rpi.gpio/: 404 Client Error: Not Found for url: https://piwheels.org/simple/rpi.gpio/ - skipping
    Using version 0.6.3 (newest of versions: 0.1.0, 0.2.0, 0.5.4, 0.5.5, 0.5.6, 0.5.7, 0.5.8, 0.5.9, 0.5.10, 0.5.11, 0.6.1, 0.6.2, 0.6.3)

**Comment by bennuttall** [comment]
This shouldn't happen. There's some sanitisation going on which is supposed to prevent this the same way PyPI does - see #20

You're using Python 3.4 which I assume means you're on Jessie?

I couldn't replicate this issue on Stretch, so perhaps pip in Jessie does something different?

Why are you using `pip3.4` rather than `pip3`?

**Comment by pintman** [comment]
I was using [picore](http://forum.tinycorelinux.net/index.php/board,57.0.html) - an arm derivative of [tinycorelinux](http://tinycorelinux.net/). There are several python version in the distribution and I installed pip with ``sudo python3.4 -m ensurepip``. After that pip3.4 was installed.

**Comment by bennuttall** [comment]
What version of pip is it? Try `pip3.4 -V`.

You might want to upgrade pip with `sudo pip3.4 install pip --upgrade` and try again.

**Comment by pintman** [comment]
The outdated version 8.0 of pip was the problem. After upgrading with ``sudo pip3.4 install --upgrade pip`` it works fine now. 

Thanks for the help. :)

Closing the issue now.

**Comment by bennuttall** [comment]
:-1:
