### ISSUE TITLE
Provenance links

### ISSUE THREAD

**Issue by tlc** [bennuttall/piwheels#65]
It'd be very nice if the search results showed (at least) a link to the pypi project page (or other source).

Your FAQ says your packages come from pypi.  But in at least one case, that's not true.  https://github.com/bennuttall/piwheels/issues/41

It's nice to know where the binaries we're downloading come from.  Even if it's pypi, the link would be a convenience.

**Comment by bennuttall** [comment]
This will be achieved with #33 and #59
