### ISSUE TITLE
psycopg2-binary wheels

### ISSUE THREAD

**Issue by cdubz** [bennuttall/piwheels#68]
The piwheels website has a wheel listing page for [psycopg2-binary](https://www.piwheels.org/simple/psycopg2-binary/), but it is empty. Ultimately a `pip install psycopg2-binary` command will end up attempting to build from source (and fail without the prerequisites).  I think this is probably something for the psycopg2 maintainers more than piwheels, but I wanted to note it just for the empty page. I looked randomly at a few other packages, including other *-binary ones and didn't find any other blanks. Is there some action for piwheels here, or just on the maintainers?

Thanks for the great service!

**Comment by bennuttall** [comment]
An empty directory means we've failed to build it. The empty directory is necessary to avoid returning a 404 error which can break pip.

I just tried `pip3 wheel psycopg2-binary` on a Pi and it failed with the error message `pg_config executable not found`. If there are build requirements to build it then I need to know what they are. Sometimes these are easy to fix, see https://github.com/bennuttall/piwheels/issues/61

What is the purpose of `psycopg2-binary`? The `psycopg2` package includes a suite of wheels on PyPI as well as sdist, and we have pi wheels for it: https://www.piwheels.org/simple/psycopg2/

**Comment by cdubz** [comment]
Basically they do not intend to release wheels for `psycopg2` from version 2.8 onwards and `psycopg2-binary` will be specifically for the wheel releases. See this post from Psycopg team for details: [Psycopg 2.7.4 released](http://initd.org/psycopg/articles/2018/02/08/psycopg-274-released/). It's a weird situation, but I sort of understand where they are coming from.

From the [Psycopg2 install instructions](http://initd.org/psycopg/docs/install.html#build-prerequisites), it appears the only build prerequisites are `python-dev` and `libpq-dev`. But note the extra info about `pg_config`:

> The pg_config program: it is usually installed by the libpq-dev package but sometimes it is not in a PATH directory. Having it in the PATH greatly streamlines the installation, so try running pg_config --version: if it returns an error or an unexpected version number then locate the directory containing the pg_config shipped with the right libpq version (usually /usr/lib/postgresql/X.Y/bin/) and add it to the PATH

Users having issues with this for a project of mine was why I changed from `psycopg2` to `psycopg2-binary` in the first place. :feelsgood:

**Comment by bennuttall** [comment]
Wow, that's nuts. Thanks for the info.

So, if `psycopg2` is to be sdist only, we can continue building pi wheels for `psycopg2`, and `pip install psycopg2` will work fine for Raspberry Pi users.

However, if `psycopg2-binary` is to be wheels only, we won't be able to build it (and I assume they won't upload arm wheels), so any Raspberry Pi users run `pip install psycopg2-binary` thinking that's how you get the binary, they won't get it (and won't get source to fall back to either).

So, amusingly, on piwheels, `psycopg2` will be binary and `psycopg2-binary` won't work.

If that's the case, we will have to copy `psycopg2` wheels to `psycopg2-binary` or simply symlink the directory, which is actually a decent solution, meaning everyone gets what they were looking for ...except people who actually wanted to build it themselves.

I suggest we do the above for now, and if any issues arise (we'll notice as we use psycopg2 in this very project!) we can just blacklist the package so it never gets built under `psycopg2`.

Sigh.

**Comment by cdubz** [comment]
Nuts, indeed. I think your workaround makes sense, but would we need to symlink each individual file so they could be named `psycopg2-binary-*`?

Also (sorry...), I note that the latest version of psycopg2 (2.7.4, released 8 Feb 2018) does not have a wheel -- currently `pip install psycopg2` fails with the same build error, but `pip install 'psycopg2<2.7.4'` does work.

**Comment by cdubz** [comment]
Sounds good. Let me know if I can do anything to help or contribute to the project in general. Thanks again for your work on this.

**Comment by bennuttall** [comment]
We now have 2.7.4 of both package names. Will leave this issue open until the two have been coupled with a symlink or similar.

**Comment by bennuttall** [comment]
It seems this problem has gone away. sdist is now uploaded to `psycopg-binary` and the file contents are exactly the same in `psycopg`. :man_shrugging:
