### ISSUE TITLE
piwheels.org DNS problems

### ISSUE THREAD

**Issue by rpaulo** [bennuttall/piwheels#69]
I'm not sure where else to leave a note, but I've been having tons of problems with the DNS service from piwheels.org.  Most of the time I get servfail or it times out.  This has been happening from multiple locations (my home network and Travis CI).

**Comment by waveform80** [comment]
We don't provide a DNS service? Just wheel downloads. If you've got a specific error message you think is related to piwheels, please feel free to include it.
