### ISSUE TITLE
Remove pyyaml 4.1

### ISSUE THREAD

**Issue by bfabio** [bennuttall/piwheels#72]
I think pyyaml 4.1 should be removed.

It was removed from PyPi because upstream considered it "badly broken" (https://github.com/yaml/pyyaml/issues/192#issuecomment-401491470) and its presence may cause headaches to whomever is using both PiPy and Piwheels as indexes (hi!).

**Comment by bennuttall** [comment]
Done! The index hasn't updated yet but the files are gone. Thanks for the heads up.
