### ISSUE TITLE
Error when I install opencv_contrib_python : libhdf5_serial.so.100: cannot open shared object file

### ISSUE THREAD

**Issue by cooldeaaap1** [bennuttall/piwheels#75]
I am sorry that :
I have use`pip install opencv_contrib_python-3.2.0.7-cp35-cp35m-linux_armv7l.whl ` and It seems OK, but when I
`python 
import cv2`

It told me that:`Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/home/pi/.pyenv/versions/3.5.2/lib/python3.5/site-packages/cv2/__init__.py", line 7, in <module> from . import cv2 ImportError: libhdf5_serial.so.100: cannot open shared object file: No such file or directory`

even`sudo apt-get update 
sudo apt-get install libhdf5-dev 
sudo apt-get update
 sudo apt-get install libhdf5-serial-dev`

It didnot work ...
How can I makr it work ?

**Comment by waveform80** [comment]
Answered in comments to skvark/opencv-python#13

**Comment by bennuttall** [comment]
General solution: https://blog.piwheels.org/how-to-work-out-the-missing-dependencies-for-a-python-package/
