### ISSUE TITLE
while install opencv-contrib-python ImportError: undefined symbol: hb_buffer_get_glyph_infos

### ISSUE THREAD

**Issue by cooldeaaap1** [bennuttall/piwheels#76]
Hi: 
Pi3b ubuntu mate1604
Python -V :3.5.2
opencv-contrib-python :3.2.0.7
 Error:
`ImportError: /usr/local/lib/python3.5/dist-packages/cv2/cv2.cpython-35m-arm-linux-gnueabihf.so: undefined symbol: hb_buffer_get_glyph_infos
`
![2018-07-26 16-26-00](https://user-images.githubusercontent.com/26562987/43250740-957cc866-90ad-11e8-83fd-26b12e6ecf93.png)

**Comment by waveform80** [comment]
Some extra detail from comments in skvark/opencv-python#13:

> @waveform80 I am sorry that : I had better to use "3.2.0.7" ,because I want to use a prject https://github.com/AirtestProject/Airtest
> and it's requirements contains "opencv-contrib-python 3.2.0.7" https://github.com/AirtestProject/Airtest/blob/master/requirements.txt

I would suggest simply modifying Airtest's requirements (or filing a bug upstream with Airtest). There's likely no reason for it to demand the precise minor version it's requesting. Either way, I'm afraid this isn't a piwheels issue (or really an opencv-python issue).
