### ISSUE TITLE
Missing package: cmake

### ISSUE THREAD

**Issue by bryan-hunt** [bennuttall/piwheels#86]
Enhancement

It would be nice if the build images had cmake installed so modules that use it to build their extensions would have access to it.

Or if the python module scikit-build were included in the python environment the cmake python module would then build and be available on piwheels (this I feel falls on the maintainer of the cmake python module - but I was just throwing it out there as an option).

**Comment by bennuttall** [comment]
The build images do have `cmake` installed. The builder script can be found here: https://github.com/bennuttall/piwheels/blob/master/deploy_slave.sh

Looking at the build log for `cmake` it seems the error is `ImportError: No module named 'skbuild'`. I'll install it on a slave to see if it builds successfully, and if so I will add it to the deploy script and it should work through building all versions.

*I'd appreciate it if you could please use our issue templates in future - this is a standard 'missing package' issue where the template would have been helpful:*

Package name: `cmake`
Link to PyPI page: https://pypi.org/project/cmake/
Version: all

**Comment by bryan-hunt** [comment]
My apologies I added that as an afterthought. So I take it in the future the strategy to request a slave configuration update I should use the missing package template and then cite my own package?

**Comment by bennuttall** [comment]
If you find a package that's missing, use the template to describe the issue, and if you have any further information (such as any dependent packages you think may be required), add that too.

My `cmake` test is still building, I'll keep an eye on it.

**Comment by bennuttall** [comment]
Some versions of `cmake` successfully built (including the latest version) so I think we're good: https://www.piwheels.org/simple/cmake/

```
   version    | abi_tag | status
--------------+---------+--------
 0.1.0        | cp35m   | f
 0.1.0        | cp34m   | f
 0.2.0        | cp35m   | f
 0.2.0        | cp35m   | f
 0.2.0        | cp34m   | f
 0.4.0        | cp35m   | f
 0.4.0        | cp34m   | f
 0.5.0        | cp35m   | f
 0.5.0        | cp35m   | f
 0.5.0        | cp34m   | f
 0.6.0        | cp35m   | f
 0.6.0        | cp34m   | f
 0.6.0        | cp35m   | f
 0.6.0        | cp34m   | f
 0.7.0        | cp35m   | f
 0.7.0        | cp34m   | f
 0.7.0        | cp35m   | f
 0.7.0        | cp34m   | f
 0.7.1        | cp35m   | f
 0.7.1        | cp34m   | f
 0.7.1        | cp35m   | f
 0.7.1        | cp34m   | f
 0.8.0        | cp35m   | f
 0.8.0        | cp34m   | f
 0.8.0        | cp35m   | f
 0.8.0        | cp34m   | f
 0.9.0        | cp35m   | f
 0.9.0        | cp35m   | f
 0.9.0        | cp34m   | f
 0.9.0        | cp34m   | f
 3.10.3       | cp34m   | t
 3.10.3       | cp34m   | t
 3.11.0       | cp34m   | f
 3.11.0       | cp34m   | f
 3.11.4       | cp34m   | t
 3.11.4       | cp34m   | t
 3.11.4.post1 | cp34m   | t
 3.11.4.post1 | cp34m   | t
 3.12.0       | cp35m   | f
 3.12.0       | cp34m   | t
 3.6.3        | cp34m   | t
 3.6.3        | cp34m   | t
 3.6.3.post1  | cp35m   | f
 3.6.3.post1  | cp35m   | f
 3.6.3.post1  | cp34m   | t
 3.6.3.post1  | cp34m   | t
 3.7.2        | cp34m   | t
 3.7.2        | cp34m   | t
 3.8.2        | cp35m   | t
 3.8.2        | cp35m   | t
 3.8.2        | cp34m   | t
 3.9.6        | cp35m   | f
 3.9.6        | cp34m   | t
 3.9.6        | cp34m   | t
```
