### ISSUE TITLE
Missing Package: hidapi

### ISSUE THREAD

**Issue by bryan-hunt** [bennuttall/piwheels#87]
Missing package
Package name: `hidapi`
Link to PyPI page: https://pypi.org/project/hidapi
Link to piwheels page: https://www.piwheels.org/simple/hidapi
Version: `all`
More information:

This module is a cython extension that requires the following packages to be installed:
* libusb-1.0-0-dev
* libudev-dev

This is the working version and should be used instead of https://pypi.org/project/hid https://www.piwheels.org/simple/hid

With those conditions satisfied the module will build and operate correctly. Verified with:
* Pi3 B V1.2
* Linux  4.14.62-v7+ #1134 SMP Tue Aug 14 17:10:10 BST 2018 armv7l GNU/Linux
* Python 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170124] on linux

**Comment by bennuttall** [comment]
Installed on builders, have kicked off rebuild attempts, should be up soon.
