### ISSUE TITLE
Adding cffi, pynacl and lxml to built wheels.

### ISSUE THREAD

**Issue by Faqa** [bennuttall/piwheels#9]
Hi,

Big fan of this project, as someone who regularly needs to build pip packages in a Pi environment.

I took a look at your build logs for those packages, and confirmed (on a docker image - https://hub.docker.com/r/resin/rpi-raspbian/) that if you add the packages libffi-dev and zlib1g-dev, cffi and pynacl will be installed correctly, and if you further add libxml2-dev and libxslt1-dev, lxml will be installed correctly.

**Comment by waveform80** [comment]
Once the current run's finished we're going to run an analysis of the build logs and figure out a reasonable set of deps to install for another run (reasonable as in "permits some sizeable majority of the failed packages to build, but doesn't require a ludicrous number of packages to be installed on the build slaves"). However, there'll definitely be some exceptions for "important" packages, e.g. PIL's important enough to warrant installing libjpeg-dev et al. even if nothing else needs it. I'd say the packages you've listed would be sufficiently important to be given that treatment too.

Leave the ticket open and it'll serve as a reminder when we get around to the analysis.

**Comment by bennuttall** [comment]
Excellent - glad we're all on the same page. Any further suggestions you have, please feel free to share on here.

The first complete production run is almost complete (every version of every package). I'm not showing build output there yet but it's on the todo list.

**Comment by Faqa** [comment]
If you add libssl-dev to that list, you can also build cryptography.

**Comment by waveform80** [comment]
PyNaCl, cffi, and cryptography should all now be available piwheels; just follow the instructions on the [homepage](https://www.piwheels.hostedpi.com/) (and make sure you're using the latest pip ... I should probably add that to the homepage).

I'm just about to start a run on some of the failed builds (I'd forgotten scipy required libblas  and liblapack but they're now installed on all the build slaves so I'm going to start a limited run of failed packages to fill in some of the ones missed).

**Comment by waveform80** [comment]
Damn ... just realized I'd missed libssl-dev in the dep list (probably built it before reading your message) so I'm betting the cryptography packages are probably missing some functionality. I'll stick them in the list to be re-built for this run.

**Comment by waveform80** [comment]
All requested packages should now be available and libssl-dev was added to the dep-list. Some of the 3.5 packages aren't built, but the system will work through them over the next few days. Closing for now but if you come across any issues with the built packages do let me know!
