### ISSUE TITLE
Import error after installing opencv-contrib-python

### ISSUE THREAD

**Issue by Veilkrand** [bennuttall/piwheels#92]
After installing `opencv-contrib-python-3.4.2.17` and importing `cv2` in python3 it shows:
`ImportError: libhdf5_serial.so.100: cannot open shared object file: No such file or directory`
I have tried to reinstall `libhdf5` and `libhdf5_serial` but it didn't resolved the problem. I have try as well to install a different version of opencv without luck. I'm using Ubuntu Mate in RPI. Any insights? Thanks

**Comment by waveform80** [comment]
> I have tried to reinstall libhdf5 and libhdf5_serial but it didn't resolved the problem. I have try as well to install a different version of opencv without luck. I'm using Ubuntu Mate in RPI. Any insights? Thanks

How did you try and reinstall them? What was the output when you tried to (re)install them?

> I'm using Ubuntu Mate in RPI. Any insights? Thanks

Hmmm; this may or may not work with piwheels; we build purely on Raspbian at the moment so Ubuntu Mate is unsupported. Still, if it's Ubuntu Mate 16.04 (xenial) there's a chance of it working as I think that's python 3.5 in which case the Raspbian Stretch built packages *might* work (but no guarantees).

**Comment by Veilkrand** [comment]
@waveform80 I have reinstalled `ibhdf5` and `libhdf5_serial` packages using apt-get with no errors. It's Ubuntu Mate (Xenial) with python 3.5. Thanks

**Comment by waveform80** [comment]
> I have reinstalled ibhdf5 and libhdf5_serial packages using apt-get with no errors

Really? That's impressive ... there's no such package as `libhdf5` or `libhdf5_serial` under Raspbian or Ubuntu.

There is a libhdf5-8 package (on Raspbian Jessie) and a libhdf5-100 package (on Raspbian Stretch), which contain the `libhdf5_serial.so.<some-version>` library. I'm curious what version Ubuntu Mate has. If it's got libhdf5-100 then something else is going on. If it's some other version of libhdf5-* then we know what the issue is: wrong dependency available from the distro.

That's why I'd like to see the output from apt-get, so I can know precisely what version we're dealing with here.

**Comment by Veilkrand** [comment]
Trying to find the missing dependency I tried to install several packages
related to ibhdf5 and libhdf5_serial, including libhdf5-* packages
and python3-h5py. What package should I install?
I have in fact `/usr/lib/arm-linux-gnueabihf/libhdf5_serial.so.10`
and `libhdf5_serial.so.10.1.0` but not `libhdf5-100`
Thanks

**Comment by waveform80** [comment]
> I have in fact `/usr/lib/arm-linux-gnueabihf/libhdf5_serial.so.10` and `libhdf5_serial.so.10.1.0` but not `libhdf5_serial.so.100` 

Ah, well I'm afraid that explains things. That simply means that Ubuntu Mate 16.04 has an older version of libhdf5_serial in its repos (10, while Raspbian Stretch has a later version, 100 - don't pay too much attention to the size of that number - apparently it jumped from version 10 to 100!). Anyway, that simply means the piwheels-built wheel won't work on Ubuntu Mate 16.04.

I've had a look on packages.ubuntu.com and apparently libhdf5-100 is artful and onwards (including bionic and cosmic) so if there's a later Ubuntu Mate (e.g. 18.04) you could try that, but of course you run the risk that other dependencies are different versions too. The only definite solution is simply to use Raspbian instead (at the moment we have no plans to extend piwheels support to Ubuntu Mate).
