### ISSUE TITLE
Package grpcio not up to date

### ISSUE THREAD

**Issue by DirkUK** [bennuttall/piwheels#93]
Missing package
Package name: `grpcio`
Link to PyPI page: https://pypi.org/project/grpcio/
Link to piwheels page: https://www.piwheels.org/simple/grpcio
Version: 1.15
More information:

Latest version on piwheels is 1.14.1 (release date 5/8/18)
After that a few more versions were released on pypi. The latest one is 1.15 (released 28/8/18)

This package is required by tensorflow and atm the source is downloaded / compiled when you install tensorflow.

**Comment by bennuttall** [comment]
Thanks - I build these ones manually because they tend to upload incompatible Arm wheels. I've built and imported 1.15 now.
